### PR TITLE
Bugfixes and dependencies update

### PR DESCRIPTION
**Pull request by brynne8**
As lua2js has been inactive for several years, the pegjs version is rather old, which is a bit incompatible with current stable version 0.11.0. Other libs also updated, and supported new syntaxes, for example escodegen now supports computed properties in objects, which is defined in [ESTree](https://github.com/estree/estree).

> Note: Some of your changes that made whitespace checking stricter are not applied in my changes, as I am a bit conservative.

I later focused on undecorated Lua objects in JS, making JS array as an alternative to object. Also, I implemented or modified some `stdlib.js` functions to make them more conformant with lua standard. 

I unified functions args and multiple return values to `LuaArgList`, which is previously called `LuaReturnValues`. Multiple args will always be an instance of `LuaArgList`, and even in Undecorated Lua Objects mode will return `LuaArgList`, as it would be ambiguous to return an JS Array.

> Another note: I changed almost all JS in index.html to ~BootCSS~jsDelivr CDN, which is faster for developement in China (as Google is inaccessible and Cloudflare is very slow in China). Including a compiled version of escodegen is because the online version on estools.github.io is too old.

Moreover, I didn't take compatibility to old browsers (IE, etc.) into account. I used ES6 freely in writing code.

### CODE REVIEW

**Comment by ca-tay** [comment]
thanks

**Comment by basicer** [comment]
Hey @AlexanderMisel.  Thanks for this!  I'm terribly sorry, but somehow this slipped though the cracks two years ago when you submitted it.  @poopyhead121's comment alerted me to it.  I'll test it out tonight and hopefully get it merged.

**Comment by ca-tay** [comment]
@basicer Wow! it's been years since anybody has responded on this repository, i was recently looking on some transpilers and i came across this, thanks!

**Comment by basicer** [comment]
@AlexanderMisel When I run the tests with these changes I get a few more test failures.  It's possible that the tests just need to be updated to a later version of lua.  What version were you targeting when you made the upgrades?

**Comment by brynne8** [comment]
The few more test failures were arisen from math functions. I found that internal object Math cannot be simply assigned to empty object `{}`, so I committed a fix.

**Comment by basicer** [comment]
Looks good, thanks!

**Pull request merged**
